---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - {role: worker-gdnsd, tags: ['worker']}
  environment:
    GIT_SSL_NO_VERIFY: 1
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  vars:
    GDNSD_PATH: /usr/local/sbin/gdnsd
    PYTHON_PATH: /usr/local/bin/python3.9
    PIP_PATH: /usr/local/bin/pip3.9
    PYTHON_VERSION: "3.9.8"
    PYTHON_CHECKSUM: "md5:d4875c1832c8f757280794f6d5e9c95f"
