---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - {role: worker-gdnsd, tags: ['worker']}
  environment:
    GIT_SSL_NO_VERIFY: 1
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  vars:
    GDNSD_PATH: /usr/local/sbin/gdnsd
    PYTHON_PATH: /usr/local/bin/python3.6
    PIP_PATH: /usr/local/bin/pip3.6
    PYTHON_VERSION: "3.6.12"
